# Generated by Django 3.1.7 on 2021-03-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='conversion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='sales_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='stream_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stream',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.user'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='stream_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
